"""
Tests for circuit2graph.expansion.

The important invariant is round-trip invertibility at primitive-block level:

    primitive raw graph -> graphlize -> expand_topology -> graphlize

must reproduce the same macro graph, and, for graphlize-produced macro graphs,
the expanded primitive graph must be isomorphic to the original primitive graph.
"""

from __future__ import annotations

from pathlib import Path
import os
import re
import sys
from typing import Callable

_THIS_FILE = Path(__file__).resolve()
_REPO_ROOT = _THIS_FILE.parents[1]
_SRC_DIR = _REPO_ROOT / "src"
if str(_SRC_DIR) not in sys.path:
    sys.path.insert(0, str(_SRC_DIR))

import pytest

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from circuit2graph.compression import graphlize
from circuit2graph.definitions import SubgType
from circuit2graph.expansion import expand_node_to_primitives, expand_topology, topologies_equivalent
from circuit2graph.topology import CQEDTopology

# Reuse already-maintained fixtures from test_graphlize.py.
from test_graphlize import (  # type: ignore
    USER_TOPOLOGY_BUILDERS,
    _cc_attrs,
    _r_attrs,
    _t_attrs,
)


PLOT_DIR = Path(os.environ.get("CQED_EXPANSION_PLOT_DIR", _REPO_ROOT / "test" / "expansion_roundtrip_plots"))


def _i_attrs(D: float = 9.0, l: float = 1.3e-4) -> dict[str, float]:
    return {"D": D, "l": l}


def _safe_filename(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", name).strip("_") or "topology"


def _plot_round_trip(raw: CQEDTopology, compressed: CQEDTopology, expanded: CQEDTopology) -> Path:
    """Save the three-step visual debug plot: primitive -> macro -> re-expanded.

    The plots are intentionally generated by the test itself, so running pytest
    gives both correctness checks and visual artifacts useful for debugging the
    expansion/compression inversion.  Override the output folder with:

        CQED_EXPANSION_PLOT_DIR=/path/to/plots pytest test/test_expansion.py
    """
    PLOT_DIR.mkdir(parents=True, exist_ok=True)
    fig, axes = plt.subplots(1, 3, figsize=(21, 6))

    for ax, topology, title in [
        (axes[0], raw, "1. INPUT primitive / inner graph"),
        (axes[1], compressed, "2. COMPRESSED macro graph"),
        (axes[2], expanded, "3. RE-EXPANDED primitive / inner graph"),
    ]:
        topology.draw(ax=ax, with_labels=True)
        ax.set_title(f"{title}\n{topology.name}", fontsize=10)

    fig.suptitle(
        f"Expansion round trip: {raw.name}\n"
        f"nodes {len(raw._nodes)} -> {len(compressed._nodes)} -> {len(expanded._nodes)}, "
        f"edges {len(raw._edges)} -> {len(compressed._edges)} -> {len(expanded._edges)}",
        fontsize=12,
    )
    fig.tight_layout()

    out_path = PLOT_DIR / f"{_safe_filename(raw.name)}__primitive_macro_reexpanded.png"
    fig.savefig(out_path, dpi=160, bbox_inches="tight")
    plt.close(fig)
    return out_path


def _assert_round_trip(raw: CQEDTopology, *, make_plot: bool = True) -> None:
    compressed = graphlize(raw)
    expanded = expand_topology(compressed, validate=True)
    recompressed = graphlize(expanded)

    assert topologies_equivalent(expanded, raw, check_labels=False), raw.name
    assert topologies_equivalent(recompressed, compressed, check_labels=False), raw.name

    if make_plot:
        plot_path = _plot_round_trip(raw, compressed, expanded)
        assert plot_path.exists(), plot_path


@pytest.mark.parametrize("name,builder", USER_TOPOLOGY_BUILDERS.items())
def test_expand_graphlize_user_examples_is_inverse(name: str, builder: Callable[[], CQEDTopology]) -> None:
    _assert_round_trip(builder())


def test_expand_single_macro_nodes_respects_direction_and_attrs() -> None:
    cases = [
        (SubgType.TC, {"L": 1.0, "C": 2.0, "Cc": 3.0, "dir": 1.0}, [SubgType.TRANSMON, SubgType.C_COUPLER]),
        (SubgType.TC, {"L": 1.0, "C": 2.0, "Cc": 3.0, "dir": -1.0}, [SubgType.C_COUPLER, SubgType.TRANSMON]),
        (SubgType.RC, {"length": 4.0, "Cc": 3.0, "dir": 1.0}, [SubgType.RESONATOR, SubgType.C_COUPLER]),
        (SubgType.RC, {"length": 4.0, "Cc": 3.0, "dir": -1.0}, [SubgType.C_COUPLER, SubgType.RESONATOR]),
        (SubgType.RI, {"length": 4.0, "D": 9.0, "l": 0.1, "dir": 1.0}, [SubgType.RESONATOR, SubgType.I_COUPLER]),
        (SubgType.RI, {"length": 4.0, "D": 9.0, "l": 0.1, "dir": -1.0}, [SubgType.I_COUPLER, SubgType.RESONATOR]),
        (SubgType.RCT, {"length": 4.0, "Cc": 3.0, "L": 1.0, "C": 2.0, "dir": 1.0}, [SubgType.RESONATOR, SubgType.C_COUPLER, SubgType.TRANSMON]),
        (SubgType.RCT, {"length": 4.0, "Cc": 3.0, "L": 1.0, "C": 2.0, "dir": -1.0}, [SubgType.TRANSMON, SubgType.C_COUPLER, SubgType.RESONATOR]),
        (SubgType.TCT, {"L": 1.0, "C": 2.0, "Cc": 3.0, "L2": 4.0, "C2": 5.0, "dir": 1.0}, [SubgType.TRANSMON, SubgType.C_COUPLER, SubgType.TRANSMON]),
    ]
    for subg_type, attrs, expected_types in cases:
        node = type("N", (), {"subg_type": subg_type, "attrs": attrs, "node_id": 17, "label": None})()
        specs = expand_node_to_primitives(node)
        assert [s.subg_type for s in specs] == expected_types


def build_feedline_two_branch_hub_plus_cycle() -> CQEDTopology:
    """Stress case similar to the screenshot: feedline hub, TCT, RC and a cycle."""
    t = CQEDTopology("feedline_two_branch_hub_plus_cycle")
    f = t.add_node(SubgType.FEEDLINE, {}, label="F")
    c_entry = t.add_node(SubgType.C_COUPLER, _cc_attrs(2e-15), label="C_entry")
    c31 = t.add_node(SubgType.C_COUPLER, _cc_attrs(3e-15), label="C31")
    r3 = t.add_node(SubgType.RESONATOR, _r_attrs(0.00334), label="R3")
    c23 = t.add_node(SubgType.C_COUPLER, _cc_attrs(4e-15), label="C23")
    t2 = t.add_node(SubgType.TRANSMON, _t_attrs(11e-9), label="T2")
    c12 = t.add_node(SubgType.C_COUPLER, _cc_attrs(5e-15), label="C12")
    t1 = t.add_node(SubgType.TRANSMON, _t_attrs(12e-9), label="T1")
    c_leaf = t.add_node(SubgType.C_COUPLER, _cc_attrs(6e-15), label="C_leaf")

    t.add_edge(f, c_entry)
    t.add_edge(c_entry, c31)
    t.add_edge(c_entry, r3)
    t.add_edge(c_entry, t1)
    t.add_edge(c31, c23)
    t.add_edge(c23, t2)
    t.add_edge(t2, c12)
    t.add_edge(c12, t1)
    t.add_edge(r3, c23)
    # disconnected-ish leaf connected to entry to make hub degree high and add an unmerged coupler leaf
    t.add_edge(c_entry, c_leaf)
    return t


def build_inductive_resonator_line_and_hub() -> CQEDTopology:
    t = CQEDTopology("inductive_resonator_line_and_hub")
    f = t.add_node(SubgType.FEEDLINE, {}, label="F")
    c = t.add_node(SubgType.C_COUPLER, _cc_attrs(1e-15), label="C_feed")
    r1 = t.add_node(SubgType.RESONATOR, _r_attrs(0.0030), label="R1")
    ind1 = t.add_node(SubgType.I_COUPLER, _i_attrs(9.0, 1e-4), label="I1")
    r2 = t.add_node(SubgType.RESONATOR, _r_attrs(0.0032), label="R2")
    ind2 = t.add_node(SubgType.I_COUPLER, _i_attrs(10.0, 2e-4), label="I2")
    r3 = t.add_node(SubgType.RESONATOR, _r_attrs(0.0034), label="R3")
    q = t.add_node(SubgType.TRANSMON, _t_attrs(13e-9), label="T")
    cq = t.add_node(SubgType.C_COUPLER, _cc_attrs(7e-15), label="Cq")
    t.add_edge(f, c); t.add_edge(c, r1)
    t.add_edge(r1, ind1); t.add_edge(ind1, r2)
    t.add_edge(r2, ind2); t.add_edge(ind2, r3)
    t.add_edge(r2, cq); t.add_edge(cq, q)
    return t


def build_four_transmon_capacitive_ring_with_tail() -> CQEDTopology:
    t = CQEDTopology("four_transmon_capacitive_ring_with_tail")
    q1 = t.add_node(SubgType.TRANSMON, _t_attrs(10e-9), label="T1")
    c12 = t.add_node(SubgType.C_COUPLER, _cc_attrs(1e-15), label="C12")
    q2 = t.add_node(SubgType.TRANSMON, _t_attrs(11e-9), label="T2")
    c23 = t.add_node(SubgType.C_COUPLER, _cc_attrs(2e-15), label="C23")
    q3 = t.add_node(SubgType.TRANSMON, _t_attrs(12e-9), label="T3")
    c34 = t.add_node(SubgType.C_COUPLER, _cc_attrs(3e-15), label="C34")
    q4 = t.add_node(SubgType.TRANSMON, _t_attrs(13e-9), label="T4")
    c41 = t.add_node(SubgType.C_COUPLER, _cc_attrs(4e-15), label="C41")
    r = t.add_node(SubgType.RESONATOR, _r_attrs(0.004), label="R_tail")
    cr = t.add_node(SubgType.C_COUPLER, _cc_attrs(5e-15), label="CR_tail")
    for a, b in [(q1, c12), (c12, q2), (q2, c23), (c23, q3), (q3, c34), (c34, q4), (q4, c41), (c41, q1), (q3, cr), (cr, r)]:
        t.add_edge(a, b)
    return t


STRESS_BUILDERS = [
    build_feedline_two_branch_hub_plus_cycle,
    build_inductive_resonator_line_and_hub,
    build_four_transmon_capacitive_ring_with_tail,
]


@pytest.mark.parametrize("builder", STRESS_BUILDERS)
def test_expand_graphlize_stress_cases_are_inverse(builder: Callable[[], CQEDTopology]) -> None:
    _assert_round_trip(builder())


def test_expand_predicted_unlabelled_macro_graph_is_recompressible() -> None:
    """Model outputs may not have compression labels; expansion must still work."""
    g = CQEDTopology("predicted_unlabelled_macro")
    c = g.add_node(SubgType.C_COUPLER, {"Cc": 1e-15}, label=None)
    tct = g.add_node(SubgType.TCT, {"L": 10e-9, "C": 70e-15, "Cc": 2e-15, "L2": 11e-9, "C2": 71e-15, "dir": 1.0}, label=None)
    rct = g.add_node(SubgType.RCT, {"length": 0.0035, "Cc": 3e-15, "L": 12e-9, "C": 72e-15, "dir": -1.0}, label=None)
    rc = g.add_node(SubgType.RC, {"length": 0.0038, "Cc": 4e-15, "dir": 1.0}, label=None)
    g.add_edge(c, tct)
    g.add_edge(c, rct)
    g.add_edge(tct, rc)

    expanded = expand_topology(g, validate=True)
    assert all(n.subg_type in {SubgType.FEEDLINE, SubgType.TRANSMON, SubgType.RESONATOR, SubgType.C_COUPLER, SubgType.I_COUPLER} for n in expanded._nodes)
    assert topologies_equivalent(graphlize(expanded), g, check_labels=False)

    # Visual debug artifact for the model-output setting: the macro graph is
    # already the input, so panel 1 and panel 2 are both macro-level, while
    # panel 3 shows the deterministic primitive expansion.
    plot_path = _plot_round_trip(graphlize(expanded), g, expanded)
    assert plot_path.exists(), plot_path
