#!/usr/bin/env python3
"""
analysis_4_3_1_seen_circuits.py
================================
Final analysis for Sec. 4.3.1 -- Inference Results: Seen Circuits.

Run this file from the BASE DIRECTORY of the cQED-Gen repository, i.e. next to
``train_vae.py``, ``inference_circuit_elements.py``,
``inference_hamiltonian_qultra.py``, ``best_vae_global.pt`` and ``src/``.

The script deliberately reuses the inference/evaluation machinery already
present in the repository. In particular it imports:

* checkpoint/model helpers and topology/parameter-alignment utilities from
  ``inference_circuit_elements.py``;
* QuLTRA simulation, observable extraction and mode-alignment utilities from
  ``inference_hamiltonian_qultra.py``.

It evaluates the TEST split only by default: the circuit topologies are therefore
seen during training, whereas the continuous parameter configurations are not.

Analyses
--------
1. Topology reconstruction, for BOTH branches
       G -> z_c -> G_hat
       H -> z_s -> G_hat

   It reports, globally and per circuit family:
       - exact typed graph-isomorphism accuracy;
       - canonical/ordered exact reconstruction accuracy (diagnostic);
       - macro-node type accuracy;
       - edge precision, recall and F1;
       - graph-size error S_N = mean |N_hat - N|;
       - direction accuracy and coverage.

   The thesis value A_topo uses the typed graph-isomorphism criterion: node
   ordering itself is not considered a physical topological error. Direction is
   deliberately excluded from topology equality and evaluated separately.

2. Repeated 500-circuit studies
   The neural inference is executed ONCE on the complete test split. Then the
   requested N independent M-circuit studies are produced by random subsampling
   the cached per-sample results (defaults: M=500, N=10). This gives mean +/- std
   without needlessly re-running the same deterministic inference ten times.
   The same bootstrap/subsampling summary is also produced family by family.

3. Residual topology-error decomposition
       - true-vs-predicted macro-node confusion matrices;
       - error rate for FEEDLINE, TRANSMON, RESONATOR, C_COUPLER, TC, RC,
         RCT, TCT, I_COUPLER and RI;
       - most common confusion for every macro-node class.

4. Continuous circuit parameters, BOTH branches
   Parameters are evaluated ONLY for type-isomorphic topologies. Predicted node
   order is first aligned through typed graph isomorphism; saved symmetry-induced
   parameter permutations are then used exactly as in the repository evaluation.
   For every family/parameter and for aggregate physical parameter classes the
   script reports:
       - median absolute relative error [%];
       - 90th percentile [%];
       - mean [%];
       - number of valid comparisons.

5. QuLTRA physical validation
   By default QuLTRA is run for the Hamiltonian-conditioned branch H -> G only,
   because this is the actual inverse-design pathway discussed in Sec. 4.3.1.
   The predicted graph is expanded and simulated through the repository QuLTRA
   workflow; modes are aligned to the target by frequency assignment.
   It reports median/P90 relative errors separately for:
       - frequencies f_i;
       - self-Kerr terms chi_ii;
       - cross-Kerr terms chi_ij;
       - decay rates kappa_i.
   Detailed per-slot/per-family results and QuLTRA failure reasons are also saved.

Default outputs
---------------
analysis_results/4_3_1_seen_circuits/
    seen_topology_full.csv
    seen_topology_runs_overall.csv
    seen_topology_runs_per_family.csv
    seen_topology_run_summary.csv
    seen_node_type_error_by_class.csv
    seen_node_confusion_counts.csv
    seen_parameter_errors_raw.csv
    seen_parameter_errors_by_family.csv
    seen_parameter_errors_aggregate.csv
    seen_hamiltonian_errors_raw.csv
    seen_hamiltonian_errors_by_family.csv
    seen_hamiltonian_errors_aggregate.csv
    seen_qultra_status.csv
    seen_final_discussion_summary.csv
    seen_inference_summary.json
    figure_seen_topology_metrics.pdf
    figure_seen_node_confusion.pdf
    figure_seen_parameter_errors.pdf
    figure_seen_hamiltonian_errors.pdf       (when QuLTRA is available/enabled)

Examples
--------
Final/default analysis:
    python analysis_4_3_1_seen_circuits.py

Fast diagnostic without QuLTRA:
    python analysis_4_3_1_seen_circuits.py --max-per-family 100 --no-qultra

Faster QuLTRA diagnostic (500 attempted samples per family):
    python analysis_4_3_1_seen_circuits.py --qultra-max-per-family 500

Run QuLTRA on both inference branches:
    python analysis_4_3_1_seen_circuits.py --qultra-branches both

Notes
-----
* Deterministic inference is the default. GraphVAE returns the posterior mean in
  eval mode, matching the methodology stated in the thesis.
* The script checks that the scaler regenerated by the deterministic loader is
  compatible with the scaler stored in the checkpoint. This is important because
  encoder features were precomputed by the loader.
* QuLTRA is expensive. By default all eligible test samples are evaluated for the selected
  QuLTRA branch. Use --qultra-max-per-family 500 (or a smaller value) for a faster diagnostic run.
"""

from __future__ import annotations

import argparse
import csv
import inspect
import json
import math
import os
import random
import sys
from collections import Counter, defaultdict
from pathlib import Path
from types import SimpleNamespace
from typing import Any, Iterable

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import torch


# ---------------------------------------------------------------------------
# Repository discovery/imports
# ---------------------------------------------------------------------------

THIS_FILE = Path(__file__).resolve()


def find_repo_root() -> Path:
    candidates = [Path.cwd(), THIS_FILE.parent, *THIS_FILE.parents, *Path.cwd().parents]
    for c in candidates:
        if (
            (c / "train_vae.py").exists()
            and (c / "src").exists()
            and (c / "inference_circuit_elements.py").exists()
        ):
            return c.resolve()
    raise RuntimeError(
        "Could not find the cQED-Gen repository root. Run this script from the "
        "directory containing train_vae.py, inference_circuit_elements.py and src/."
    )


REPO_ROOT = find_repo_root()
SRC_ROOT = REPO_ROOT / "src"
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))
os.chdir(REPO_ROOT)

# Reuse the repository's actual analysis/inference code.
import inference_circuit_elements as ice  # noqa: E402
try:
    import inference_hamiltonian_qultra as ihq  # noqa: E402
except Exception as exc:  # QuLTRA analysis is optional; topology/params still work.
    ihq = None
    _IHQ_IMPORT_ERROR = exc
else:
    _IHQ_IMPORT_ERROR = None

from data_loader.loader_vae import load_all_datasets_vae  # noqa: E402
from data_loader.schema import train_datasets  # noqa: E402
from circuit2graph import SubgType, SUBG_DEFS  # noqa: E402


FAMILY_NAMES = {
    "Qubit": "Qubit",
    "Resonator": "Resonator",
    "Qubit_resonator_feedline_capacitive": "Q-R-F (capacitive)",
    "Qubit_resonator_feedline_inductive_nognd": "Q-R-F (inductive)",
    "Qubit_resonator_resonator": "Q-R-R",
    "Resonator_qubit_resonator": "R-Q-R",
    "Two_qubit_with_capacitive_coupling": "Two-qubit capacitive",
    "Three_qubit_capacitive_star": "Three-qubit star",
}

NODE_LABELS = [st.name for st in SubgType]
NONE_NODE = "<none>"

PARAMETER_DISPLAY = {
    "L": "L",
    "L2": "L",
    "C": "C",
    "C2": "C",
    "Cc": "Cc",
    "Cc_qr": "Cc_qr",
    "Cc_rf": "Cc_rf",
    "length": "length",
    "D": "D",
    "l": "l",
}


# ---------------------------------------------------------------------------
# Generic utilities
# ---------------------------------------------------------------------------


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def pretty_family(name: str) -> str:
    return FAMILY_NAMES.get(name, name.replace("_", " "))


def finite_or_nan(x: Any) -> float:
    try:
        y = float(x)
    except Exception:
        return float("nan")
    return y if np.isfinite(y) else float("nan")


def write_csv(rows: list[dict[str, Any]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fields: list[str] = []
    seen = set()
    for row in rows:
        for key in row:
            if key not in seen:
                fields.append(key)
                seen.add(key)
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)


def jsonable(obj: Any) -> Any:
    if isinstance(obj, dict):
        return {str(k): jsonable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [jsonable(v) for v in obj]
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, (np.integer, np.floating)):
        return obj.item()
    if isinstance(obj, Path):
        return str(obj)
    if isinstance(obj, float) and not np.isfinite(obj):
        return None
    return obj


def safe_mean(values: Iterable[float]) -> float:
    a = np.asarray(list(values), dtype=float)
    a = a[np.isfinite(a)]
    return float(np.mean(a)) if a.size else float("nan")


def safe_std(values: Iterable[float], ddof: int = 1) -> float:
    a = np.asarray(list(values), dtype=float)
    a = a[np.isfinite(a)]
    if a.size == 0:
        return float("nan")
    if a.size <= ddof:
        return 0.0
    return float(np.std(a, ddof=ddof))


def percentile(values: Iterable[float], q: float) -> float:
    a = np.asarray(list(values), dtype=float)
    a = a[np.isfinite(a)]
    return float(np.percentile(a, q)) if a.size else float("nan")


def rel_err_percent(true: float | np.ndarray, pred: float | np.ndarray, eps: float = 1e-30) -> np.ndarray:
    t = np.asarray(true, dtype=np.float64)
    p = np.asarray(pred, dtype=np.float64)
    return np.abs(p - t) / np.maximum(np.abs(t), eps) * 100.0


def base_attr_name(name: str) -> str:
    # Remove duplicate-node suffix introduced by the evaluation helper.
    base = name.rsplit("_n", 1)[0] if "_n" in name else name
    return PARAMETER_DISPLAY.get(base, base)


def group_by_family(samples: list[Any]) -> dict[str, list[Any]]:
    out: dict[str, list[Any]] = defaultdict(list)
    for s in samples:
        out[str(s.dataset_name)].append(s)
    return dict(out)


def optionally_limit_per_family(samples: list[Any], n: int, seed: int) -> list[Any]:
    if n <= 0:
        return list(samples)
    rng = np.random.default_rng(seed)
    out: list[Any] = []
    for family, items in sorted(group_by_family(samples).items()):
        if len(items) <= n:
            chosen = list(items)
        else:
            idx = rng.choice(len(items), size=n, replace=False)
            chosen = [items[int(i)] for i in idx]
        out.extend(chosen)
    rng.shuffle(out)
    return out


# ---------------------------------------------------------------------------
# Scaler consistency check
# ---------------------------------------------------------------------------


def _scaler_arrays(ds_scaler: Any) -> list[np.ndarray]:
    out = []
    for obj in (getattr(ds_scaler, "param_scaler", None), getattr(ds_scaler, "obs_scaler", None)):
        if obj is None:
            continue
        for attr in ("mean_", "std_"):
            arr = getattr(obj, attr, None)
            if arr is not None:
                out.append(np.asarray(arr, dtype=np.float64))
    return out


def checkpoint_scalers_for_families(checkpoint_scalers: dict[str, Any], fresh_scalers: dict[str, Any]) -> dict[str, Any]:
    """Return checkpoint scalers mapped to every training family.

    New global-scaler checkpoints normally contain both the family aliases and
    ``__global__``. Older/simplified checkpoints may contain only ``__global__``.
    """
    out = dict(checkpoint_scalers or {})
    global_sc = out.get("__global__")
    if global_sc is not None:
        for family in train_datasets():
            out.setdefault(family, global_sc)
    # A missing checkpoint scaler is allowed only as a fallback; this is printed
    # explicitly so the final analysis is never silently using a different scaler.
    for family, sc in fresh_scalers.items():
        if family == "__global__":
            continue
        if family not in out:
            print(f"WARNING: checkpoint scaler missing for {family}; using freshly reconstructed scaler.")
            out[family] = sc
    return out


def verify_scaler_consistency(checkpoint_scalers: dict[str, Any], fresh_scalers: dict[str, Any], atol: float = 1e-9) -> None:
    families = [f for f in train_datasets() if f in fresh_scalers and f in checkpoint_scalers]
    worst = 0.0
    worst_family = None
    for family in families:
        a = _scaler_arrays(checkpoint_scalers[family])
        b = _scaler_arrays(fresh_scalers[family])
        if len(a) != len(b):
            raise RuntimeError(f"Scaler structure mismatch for {family}.")
        for x, y in zip(a, b):
            if x.shape != y.shape:
                raise RuntimeError(f"Scaler shape mismatch for {family}: {x.shape} vs {y.shape}.")
            d = float(np.max(np.abs(x - y))) if x.size else 0.0
            if d > worst:
                worst = d
                worst_family = family
    print(f"Scaler consistency: max |checkpoint-fresh| = {worst:.3e}" + (f" ({worst_family})" if worst_family else ""))
    if worst > atol:
        raise RuntimeError(
            "The dataset scaler reconstructed by the current repository/data does not match the scaler "
            f"stored in the checkpoint (max difference {worst:.3e} > {atol:.1e}). "
            "Because encoder features are precomputed by the loader, continuing would mix incompatible "
            "normalizations. Use the exact repository/data used for the final training run."
        )


# ---------------------------------------------------------------------------
# Typed graph isomorphism and topology decomposition
# ---------------------------------------------------------------------------


def nx_typed_graph(g: Any) -> nx.Graph:
    G = nx.Graph()
    for i, st in enumerate(g.node_types):
        G.add_node(int(i), node_type=int(st))
    for u, v in g.edges:
        if int(u) != int(v):
            G.add_edge(int(u), int(v))
    return G


def typed_isomorphism_mapping(g_true: Any, g_pred: Any) -> dict[int, int] | None:
    if len(g_true.node_types) != len(g_pred.node_types):
        return None
    if len(g_true.edges) != len(g_pred.edges):
        # Isomorphic simple graphs must have equal edge counts; cheap early exit.
        return None
    Gt = nx_typed_graph(g_true)
    Gp = nx_typed_graph(g_pred)
    matcher = nx.algorithms.isomorphism.GraphMatcher(
        Gt,
        Gp,
        node_match=lambda a, b: int(a["node_type"]) == int(b["node_type"]),
    )
    try:
        return next(matcher.isomorphisms_iter())
    except StopIteration:
        return None


def reorder_pred_to_true(g_pred: Any, true_to_pred: dict[int, int], n_true: int) -> SimpleNamespace:
    pred_to_true = {int(p): int(t) for t, p in true_to_pred.items()}
    node_types = [int(g_pred.node_types[int(true_to_pred[i])]) for i in range(n_true)]
    attrs_src = getattr(g_pred, "attrs", []) or []
    attrs = []
    for i in range(n_true):
        p = int(true_to_pred[i])
        attrs.append(dict(attrs_src[p]) if p < len(attrs_src) else {})
    edges = []
    seen = set()
    for u, v in getattr(g_pred, "edges", []) or []:
        if int(u) not in pred_to_true or int(v) not in pred_to_true:
            continue
        a, b = pred_to_true[int(u)], pred_to_true[int(v)]
        if a == b:
            continue
        key = tuple(sorted((a, b)))
        if key not in seen:
            seen.add(key)
            edges.append(key)
    return SimpleNamespace(node_types=node_types, edges=edges, attrs=attrs)


def _direction_value(attrs: dict[str, Any] | None) -> float:
    if not attrs:
        return float("nan")
    for key in ("dir", "direction"):
        if key in attrs:
            try:
                return float(attrs[key])
            except Exception:
                return float("nan")
    return float("nan")


def topology_record(family: str, branch: str, g_true: Any, g_pred: Any) -> tuple[dict[str, Any], list[tuple[str, str]], Any]:
    """Return topology metrics, node confusion pairs, and pred graph aligned if isomorphic."""
    repo_tm = ice.topo_match(g_true.node_types, g_true.edges, g_pred.node_types, g_pred.edges)
    mapping = typed_isomorphism_mapping(g_true, g_pred)
    exact_iso = mapping is not None
    g_pred_aligned = reorder_pred_to_true(g_pred, mapping, len(g_true.node_types)) if mapping else None

    # Node-type comparison: use the physical/isomorphic mapping where available;
    # otherwise fall back to the decoder's canonical sequence positions.
    node_pairs: list[tuple[str, str]] = []
    n_correct = 0
    n_true = len(g_true.node_types)
    n_pred = len(g_pred.node_types)
    if mapping is not None:
        for ti, t in enumerate(g_true.node_types):
            pi = int(mapping[ti])
            p = g_pred.node_types[pi]
            ts = SubgType(int(t)).name
            ps = SubgType(int(p)).name
            node_pairs.append((ts, ps))
            n_correct += int(int(t) == int(p))
        # no extras possible for an isomorphism
    else:
        n_max = max(n_true, n_pred)
        for i in range(n_max):
            ts = SubgType(int(g_true.node_types[i])).name if i < n_true else NONE_NODE
            ps = SubgType(int(g_pred.node_types[i])).name if i < n_pred else NONE_NODE
            node_pairs.append((ts, ps))
            if i < n_true and i < n_pred and int(g_true.node_types[i]) == int(g_pred.node_types[i]):
                n_correct += 1

    # Edge metrics are order-independent when an isomorphism exists. Otherwise
    # retain the repository canonical-index decomposition.
    if exact_iso:
        edge_tp = len(g_true.edges)
        edge_fp = 0
        edge_fn = 0
    else:
        edge_tp = int(repo_tm["edge_tp"])
        edge_fp = int(repo_tm["edge_fp"])
        edge_fn = int(repo_tm["edge_fn"])

    # Direction is not part of the topology-equality criterion.
    dir_true = 0
    dir_valid = 0
    dir_correct = 0
    true_attrs = getattr(g_true, "attrs", []) or []
    pred_attrs = getattr(g_pred, "attrs", []) or []
    for ti, attrs_t in enumerate(true_attrs):
        dt = _direction_value(attrs_t)
        if not np.isfinite(dt):
            continue
        dir_true += 1
        if mapping is not None:
            pi = int(mapping[ti])
        else:
            pi = ti
        if pi >= len(pred_attrs) or pi >= len(g_pred.node_types):
            continue
        if int(g_pred.node_types[pi]) != int(g_true.node_types[ti]):
            continue
        dp = _direction_value(pred_attrs[pi])
        if not np.isfinite(dp):
            continue
        dir_valid += 1
        dir_correct += int((dp >= 0) == (dt >= 0))

    rec = {
        "branch": branch,
        "family": family,
        "family_display": pretty_family(family),
        "exact_isomorphic": int(exact_iso),
        "exact_ordered": int(bool(repo_tm["exact"])),
        "n_true": n_true,
        "n_pred": n_pred,
        "abs_node_count_error": abs(n_pred - n_true),
        "n_correct_nodes": n_correct,
        "edge_tp": edge_tp,
        "edge_fp": edge_fp,
        "edge_fn": edge_fn,
        "dir_n_true": dir_true,
        "dir_n_valid": dir_valid,
        "dir_n_correct": dir_correct,
    }
    return rec, node_pairs, g_pred_aligned


def aggregate_topology(records: list[dict[str, Any]]) -> dict[str, float]:
    if not records:
        return {
            "n_samples": 0,
            "topology_accuracy": float("nan"),
            "ordered_topology_accuracy": float("nan"),
            "node_type_accuracy": float("nan"),
            "edge_precision": float("nan"),
            "edge_recall": float("nan"),
            "edge_f1": float("nan"),
            "node_count_mae": float("nan"),
            "direction_accuracy": float("nan"),
            "direction_coverage": float("nan"),
        }
    n = len(records)
    n_true = sum(int(r["n_true"]) for r in records)
    n_correct = sum(int(r["n_correct_nodes"]) for r in records)
    tp = sum(int(r["edge_tp"]) for r in records)
    fp = sum(int(r["edge_fp"]) for r in records)
    fn = sum(int(r["edge_fn"]) for r in records)
    p = tp / (tp + fp) if tp + fp else float("nan")
    r = tp / (tp + fn) if tp + fn else float("nan")
    f1 = 2 * p * r / (p + r) if np.isfinite(p) and np.isfinite(r) and p + r else float("nan")
    d_true = sum(int(x["dir_n_true"]) for x in records)
    d_valid = sum(int(x["dir_n_valid"]) for x in records)
    d_corr = sum(int(x["dir_n_correct"]) for x in records)
    return {
        "n_samples": n,
        "topology_accuracy": float(np.mean([r_["exact_isomorphic"] for r_ in records])),
        "ordered_topology_accuracy": float(np.mean([r_["exact_ordered"] for r_ in records])),
        "node_type_accuracy": n_correct / max(n_true, 1),
        "edge_precision": p,
        "edge_recall": r,
        "edge_f1": f1,
        "node_count_mae": float(np.mean([r_["abs_node_count_error"] for r_ in records])),
        "direction_accuracy": d_corr / d_valid if d_valid else float("nan"),
        "direction_coverage": d_valid / d_true if d_true else float("nan"),
        "n_exact": int(sum(int(r_["exact_isomorphic"]) for r_ in records)),
        "n_exact_ordered": int(sum(int(r_["exact_ordered"]) for r_ in records)),
    }


# ---------------------------------------------------------------------------
# Parameter and Hamiltonian record aggregation
# ---------------------------------------------------------------------------


def aggregate_error_rows(
    rows: list[dict[str, Any]],
    group_keys: list[str],
    error_key: str = "relative_error_percent",
) -> list[dict[str, Any]]:
    grouped: dict[tuple[Any, ...], list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        grouped[tuple(row.get(k) for k in group_keys)].append(row)
    out: list[dict[str, Any]] = []
    for key, items in sorted(grouped.items(), key=lambda kv: tuple(str(x) for x in kv[0])):
        vals = np.asarray([finite_or_nan(x.get(error_key)) for x in items], dtype=float)
        vals = vals[np.isfinite(vals)]
        rec = {k: v for k, v in zip(group_keys, key)}
        rec.update({
            "n": int(vals.size),
            "median_relative_error_percent": float(np.median(vals)) if vals.size else float("nan"),
            "p90_relative_error_percent": float(np.percentile(vals, 90)) if vals.size else float("nan"),
            "mean_relative_error_percent": float(np.mean(vals)) if vals.size else float("nan"),
        })
        out.append(rec)
    return out


def hamiltonian_rows_from_record(branch: str, family: str, rec: dict[str, Any]) -> list[dict[str, Any]]:
    out: list[dict[str, Any]] = []
    true = rec.get("true", {})
    pred = rec.get("pred_aligned", {})

    tf = np.asarray(true.get("frequencies", []), dtype=float)
    pf = np.asarray(pred.get("frequencies", []), dtype=float)
    for i in range(min(len(tf), len(pf))):
        if np.isfinite(tf[i]) and np.isfinite(pf[i]):
            out.append({
                "branch": branch,
                "family": family,
                "family_display": pretty_family(family),
                "category": "frequency",
                "observable": f"f_{i+1}",
                "true": float(tf[i]),
                "pred": float(pf[i]),
                "absolute_error": float(abs(pf[i] - tf[i])),
                "relative_error_percent": float(rel_err_percent(tf[i], pf[i])),
                "near_zero_true": int(abs(tf[i]) < 1e-12),
            })

    tk = np.asarray(true.get("kappa", []), dtype=float)
    pk = np.asarray(pred.get("kappa", []), dtype=float)
    for i in range(min(len(tk), len(pk))):
        if np.isfinite(tk[i]) and np.isfinite(pk[i]):
            out.append({
                "branch": branch,
                "family": family,
                "family_display": pretty_family(family),
                "category": "kappa",
                "observable": f"kappa_{i+1}",
                "true": float(tk[i]),
                "pred": float(pk[i]),
                "absolute_error": float(abs(pk[i] - tk[i])),
                "relative_error_percent": float(rel_err_percent(tk[i], pk[i])),
                "near_zero_true": int(abs(tk[i]) < 1e-12),
            })

    tc = np.asarray(true.get("chi", np.zeros((0, 0))), dtype=float)
    pc = np.asarray(pred.get("chi", np.zeros((0, 0))), dtype=float)
    n = min(tc.shape[0] if tc.ndim == 2 else 0, pc.shape[0] if pc.ndim == 2 else 0)
    for i in range(n):
        for j in range(i, n):
            if not (np.isfinite(tc[i, j]) and np.isfinite(pc[i, j])):
                continue
            category = "self_kerr" if i == j else "cross_kerr"
            out.append({
                "branch": branch,
                "family": family,
                "family_display": pretty_family(family),
                "category": category,
                "observable": f"chi_{i+1}{j+1}",
                "true": float(tc[i, j]),
                "pred": float(pc[i, j]),
                "absolute_error": float(abs(pc[i, j] - tc[i, j])),
                "relative_error_percent": float(rel_err_percent(tc[i, j], pc[i, j])),
                "near_zero_true": int(abs(tc[i, j]) < 1e-12),
            })
    return out


# ---------------------------------------------------------------------------
# Main branch evaluation
# ---------------------------------------------------------------------------


@torch.no_grad()
def evaluate_branch(
    model: Any,
    data: list[Any],
    scalers: dict[str, Any],
    device: torch.device,
    branch: str,
    batch_size: int,
    stochastic: bool,
    use_permutation_eval: bool,
    qultra_enabled: bool,
    qultra_max_per_family: int,
    f_min: float,
    f_max: float,
    seed: int,
) -> dict[str, Any]:
    assert branch in {"circuit", "spec"}
    model.eval()
    grouped = group_by_family(data)
    ds_map = ice._get_dataset_id_mapping(data)

    topo_records: list[dict[str, Any]] = []
    confusion_pairs: list[dict[str, Any]] = []
    parameter_rows: list[dict[str, Any]] = []
    hamiltonian_rows: list[dict[str, Any]] = []
    qultra_status: list[dict[str, Any]] = []

    qu = None
    if qultra_enabled:
        if ihq is None:
            print(f"WARNING: inference_hamiltonian_qultra.py could not be imported: {_IHQ_IMPORT_ERROR}")
            qultra_enabled = False
        elif not getattr(ihq, "_HAS_QULTRA_WORKFLOW", False):
            print("WARNING: repository QuLTRA workflow is unavailable; skipping Hamiltonian validation.")
            qultra_enabled = False
        else:
            try:
                qu = ihq.import_qultra()
            except Exception as exc:
                print(f"WARNING: QuLTRA import failed ({type(exc).__name__}: {exc}); skipping Hamiltonian validation.")
                qultra_enabled = False

    rng = np.random.default_rng(seed + (0 if branch == "circuit" else 10000))

    for family, samples in sorted(grouped.items()):
        print(f"\n[{branch}] {pretty_family(family)}: N={len(samples)}")
        scaler_bundle = scalers[family]
        param_scaler = scaler_bundle.param_scaler
        obs_scaler = scaler_bundle.obs_scaler

        if qultra_enabled:
            if qultra_max_per_family <= 0 or qultra_max_per_family >= len(samples):
                qultra_positions = set(range(len(samples)))
            else:
                qultra_positions = set(int(i) for i in rng.choice(len(samples), size=qultra_max_per_family, replace=False))
        else:
            qultra_positions = set()

        n_qultra_attempted = 0
        n_qultra_success = 0
        fail_reasons = Counter()

        for start in range(0, len(samples), batch_size):
            batch = samples[start:start + batch_size]
            if branch == "circuit":
                z, _, _ = model.encode(batch, scalers)
            else:
                obs_vals = torch.stack([s.obs_vals for s in batch], dim=0).to(device)
                obs_mask = torch.stack([s.obs_mask for s in batch], dim=0).to(device)
                z, _, _ = model.spec_encoder.encode(obs_vals, obs_mask)

            graphs_pred, _ = ice._decode_graphs(model, z, batch, stochastic, ds_map)

            for local_i, (sample, g_pred) in enumerate(zip(batch, graphs_pred)):
                family_i = start + local_i
                # sample.y is scaled; the graph object is sufficient for true types/edges/dir.
                g_true = ice.data_to_graph_ns(sample, param_scaler)
                trec, pairs, g_pred_aligned = topology_record(family, branch, g_true, g_pred)
                trec["sample_index_in_family"] = family_i
                topo_records.append(trec)
                for t, p in pairs:
                    confusion_pairs.append({
                        "branch": branch,
                        "family": family,
                        "family_display": pretty_family(family),
                        "true_node_type": t,
                        "pred_node_type": p,
                    })

                # ------------------------------------------------------
                # Circuit parameters: only physically matching topology.
                # ------------------------------------------------------
                if g_pred_aligned is not None and getattr(g_pred_aligned, "attrs", None):
                    true_row_scaled = np.asarray(sample.y.detach().cpu().numpy(), dtype=float)
                    pred_row_scaled = np.asarray(ice._scaled_attr_row_from_pred_graph(g_pred_aligned), dtype=float)
                    attr_names = ice._unique_attr_names_from_graph(g_true)
                    if len(pred_row_scaled) == len(true_row_scaled) == len(attr_names):
                        if use_permutation_eval:
                            perms = ice._get_attr_perm_indices(sample, len(true_row_scaled))
                            pred_row_scaled, _, _ = ice._best_pred_row_aligned_to_true_order(
                                true_row_scaled, pred_row_scaled, perms
                            )
                            pred_row_scaled = np.asarray(pred_row_scaled, dtype=float)

                        inverse_names = [name.rsplit("_n", 1)[0] if "_n" in name else name for name in attr_names]
                        true_phys = param_scaler.inverse_transform(true_row_scaled, inverse_names)
                        pred_phys = param_scaler.inverse_transform(pred_row_scaled, inverse_names)
                        for name, tv, pv in zip(attr_names, true_phys, pred_phys):
                            if not (np.isfinite(tv) and np.isfinite(pv)):
                                continue
                            parameter_rows.append({
                                "branch": branch,
                                "family": family,
                                "family_display": pretty_family(family),
                                "parameter": name,
                                "parameter_base": base_attr_name(name),
                                "true": float(tv),
                                "pred": float(pv),
                                "relative_error_percent": float(rel_err_percent(tv, pv)),
                            })

                # ------------------------------------------------------
                # QuLTRA validation: reuse the repository evaluator.
                # Reordered predicted graph makes the evaluator robust to a
                # physically irrelevant decoder-node permutation.
                # ------------------------------------------------------
                if family_i in qultra_positions:
                    n_qultra_attempted += 1
                    if g_pred_aligned is None:
                        fail_reasons["topology_not_isomorphic"] += 1
                    else:
                        try:
                            qrec, _tm, reason = ihq._maybe_physics_eval_sample(
                                sample,
                                g_pred_aligned,
                                param_scaler,
                                obs_scaler,
                                qu,
                                f_min,
                                f_max,
                                use_permutation_eval,
                            )
                        except Exception as exc:
                            qrec = None
                            reason = f"exception:{type(exc).__name__}"
                        if qrec is None:
                            fail_reasons[reason or "unknown"] += 1
                        else:
                            n_qultra_success += 1
                            hamiltonian_rows.extend(hamiltonian_rows_from_record(branch, family, qrec))

            if len(samples) >= 1000 and (start == 0 or (start // batch_size + 1) % 10 == 0):
                print(f"  {min(start + len(batch), len(samples))}/{len(samples)}")

        qultra_status.append({
            "branch": branch,
            "family": family,
            "family_display": pretty_family(family),
            "qultra_enabled": int(qultra_enabled),
            "qultra_attempted": n_qultra_attempted,
            "qultra_successful": n_qultra_success,
            "qultra_success_fraction": n_qultra_success / n_qultra_attempted if n_qultra_attempted else float("nan"),
            "failure_reasons": json.dumps(dict(fail_reasons), sort_keys=True),
        })

    return {
        "topology_records": topo_records,
        "confusion_pairs": confusion_pairs,
        "parameter_rows": parameter_rows,
        "hamiltonian_rows": hamiltonian_rows,
        "qultra_status": qultra_status,
    }


# ---------------------------------------------------------------------------
# Repeated M-circuit analyses
# ---------------------------------------------------------------------------


def repeated_topology_studies(
    records: list[dict[str, Any]],
    runs: int,
    samples_per_run: int,
    seed: int,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Overall and family-wise independent random M-sample studies."""
    rng = np.random.default_rng(seed)
    overall_rows: list[dict[str, Any]] = []
    family_rows: list[dict[str, Any]] = []

    by_branch: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for r in records:
        by_branch[str(r["branch"])].append(r)

    for branch, items in sorted(by_branch.items()):
        for run in range(runs):
            m = min(samples_per_run, len(items)) if samples_per_run > 0 else len(items)
            idx = rng.choice(len(items), size=m, replace=False)
            subset = [items[int(i)] for i in idx]
            metric = aggregate_topology(subset)
            overall_rows.append({"branch": branch, "run": run + 1, **metric})

        families = sorted({str(r["family"]) for r in items})
        for family in families:
            fam_items = [r for r in items if r["family"] == family]
            for run in range(runs):
                m = min(samples_per_run, len(fam_items)) if samples_per_run > 0 else len(fam_items)
                idx = rng.choice(len(fam_items), size=m, replace=False)
                subset = [fam_items[int(i)] for i in idx]
                metric = aggregate_topology(subset)
                family_rows.append({
                    "branch": branch,
                    "family": family,
                    "family_display": pretty_family(family),
                    "run": run + 1,
                    **metric,
                })
    return overall_rows, family_rows


def summarize_run_rows(rows: list[dict[str, Any]], group_keys: list[str]) -> list[dict[str, Any]]:
    metrics = [
        "topology_accuracy",
        "ordered_topology_accuracy",
        "node_type_accuracy",
        "edge_precision",
        "edge_recall",
        "edge_f1",
        "node_count_mae",
        "direction_accuracy",
    ]
    grouped: dict[tuple[Any, ...], list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        grouped[tuple(row.get(k) for k in group_keys)].append(row)
    out = []
    for key, items in sorted(grouped.items(), key=lambda kv: tuple(str(x) for x in kv[0])):
        rec = {k: v for k, v in zip(group_keys, key)}
        for metric in metrics:
            vals = [finite_or_nan(x.get(metric)) for x in items]
            rec[f"{metric}_mean"] = safe_mean(vals)
            rec[f"{metric}_std"] = safe_std(vals)
        rec["n_runs"] = len(items)
        rec["samples_per_run"] = items[0].get("n_samples", 0) if items else 0
        out.append(rec)
    return out


# ---------------------------------------------------------------------------
# Node-class statistics
# ---------------------------------------------------------------------------


def node_class_error_rows(confusion_pairs: list[dict[str, Any]]) -> list[dict[str, Any]]:
    grouped: dict[tuple[str, str], list[dict[str, Any]]] = defaultdict(list)
    # Overall only here; family-specific raw counts remain in seen_node_confusion_counts.csv.
    for r in confusion_pairs:
        if r["true_node_type"] != NONE_NODE:
            grouped[(r["branch"], r["true_node_type"])].append(r)
    out = []
    for (branch, true_type), items in sorted(grouped.items()):
        counts = Counter(str(x["pred_node_type"]) for x in items)
        correct = counts.get(true_type, 0)
        wrong = len(items) - correct
        wrong_counts = [(k, v) for k, v in counts.items() if k != true_type]
        wrong_counts.sort(key=lambda kv: (-kv[1], kv[0]))
        out.append({
            "branch": branch,
            "node_type": true_type,
            "n_true": len(items),
            "n_correct": correct,
            "n_wrong": wrong,
            "accuracy": correct / len(items) if items else float("nan"),
            "error_rate": wrong / len(items) if items else float("nan"),
            "most_common_wrong_prediction": wrong_counts[0][0] if wrong_counts else "",
            "most_common_wrong_count": wrong_counts[0][1] if wrong_counts else 0,
        })
    return out


def confusion_count_rows(confusion_pairs: list[dict[str, Any]]) -> list[dict[str, Any]]:
    counter = Counter((r["branch"], r["family"], r["true_node_type"], r["pred_node_type"]) for r in confusion_pairs)
    return [
        {
            "branch": b,
            "family": f,
            "family_display": pretty_family(f),
            "true_node_type": t,
            "pred_node_type": p,
            "count": n,
        }
        for (b, f, t, p), n in sorted(counter.items())
    ]


# ---------------------------------------------------------------------------
# Plotting -- PDF only
# ---------------------------------------------------------------------------


def plot_topology_metrics(full_rows: list[dict[str, Any]], out_path: Path) -> None:
    families = [f for f in FAMILY_NAMES if any(r.get("family") == f for r in full_rows)]
    branches = ["circuit", "spec"]
    branch_labels = {"circuit": r"$G\rightarrow G$", "spec": r"$H\rightarrow G$"}
    metrics = [
        ("topology_accuracy", "Exact topology"),
        ("node_type_accuracy", "Node type"),
        ("edge_f1", "Edge F1"),
    ]
    if not families:
        return
    fig, axes = plt.subplots(len(metrics), 1, figsize=(8.4, 8.2), sharex=True)
    x = np.arange(len(families), dtype=float)
    width = 0.36
    for ax, (key, title) in zip(axes, metrics):
        for bi, branch in enumerate(branches):
            vals = []
            for family in families:
                match = [r for r in full_rows if r.get("scope") == "family" and r.get("family") == family and r.get("branch") == branch]
                vals.append(float(match[0].get(key, np.nan)) if match else np.nan)
            offset = (bi - 0.5) * width
            ax.bar(x + offset, vals, width=width, label=branch_labels[branch] if ax is axes[0] else None)
        ax.set_ylim(0, 1.03)
        ax.set_ylabel(title)
        ax.grid(axis="y", alpha=0.2)
    axes[0].legend(frameon=False, ncol=2)
    axes[-1].set_xticks(x)
    axes[-1].set_xticklabels([pretty_family(f) for f in families], rotation=25, ha="right")
    axes[-1].set_xlabel("Seen circuit family")
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, bbox_inches="tight")
    plt.close(fig)


def plot_confusion(confusion_pairs: list[dict[str, Any]], out_path: Path) -> None:
    labels = NODE_LABELS + [NONE_NODE]
    idx = {name: i for i, name in enumerate(labels)}
    fig, axes = plt.subplots(1, 2, figsize=(13.2, 5.7))
    for ax, branch, title in zip(axes, ["circuit", "spec"], [r"$G\rightarrow G$", r"$H\rightarrow G$"]):
        mat = np.zeros((len(labels), len(labels)), dtype=float)
        for r in confusion_pairs:
            if r["branch"] != branch:
                continue
            mat[idx[r["true_node_type"]], idx[r["pred_node_type"]]] += 1
        row_sum = mat.sum(axis=1, keepdims=True)
        norm = np.divide(mat, row_sum, out=np.zeros_like(mat), where=row_sum > 0)
        im = ax.imshow(norm, vmin=0.0, vmax=1.0, cmap="Blues", aspect="auto")
        ax.set_title(title)
        ax.set_xlabel("Predicted macro-node type")
        ax.set_ylabel("True macro-node type")
        ax.set_xticks(range(len(labels)))
        ax.set_yticks(range(len(labels)))
        ax.set_xticklabels(labels, rotation=60, ha="right", fontsize=7)
        ax.set_yticklabels(labels, fontsize=7)
        # annotate only non-negligible cells to avoid clutter
        for i in range(len(labels)):
            for j in range(len(labels)):
                if norm[i, j] >= 0.02:
                    ax.text(j, i, f"{norm[i,j]:.2f}", ha="center", va="center", fontsize=6,
                            color="white" if norm[i, j] > 0.55 else "black")
    fig.colorbar(im, ax=axes.ravel().tolist(), fraction=0.025, pad=0.02, label="Row-normalized fraction")
    fig.subplots_adjust(left=0.08, right=0.91, bottom=0.24, top=0.90, wspace=0.30)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, bbox_inches="tight")
    plt.close(fig)


def plot_parameter_errors(aggregate_rows: list[dict[str, Any]], out_path: Path) -> None:
    params = sorted({str(r["parameter_base"]) for r in aggregate_rows})
    if not params:
        return
    branches = ["circuit", "spec"]
    x = np.arange(len(params), dtype=float)
    width = 0.36
    fig, ax = plt.subplots(figsize=(9.0, 4.8))
    positive_vals = []
    for bi, branch in enumerate(branches):
        med, p90 = [], []
        for p in params:
            m = [r for r in aggregate_rows if r["branch"] == branch and r["parameter_base"] == p]
            med.append(float(m[0]["median_relative_error_percent"]) if m else np.nan)
            p90.append(float(m[0]["p90_relative_error_percent"]) if m else np.nan)
        vals = np.asarray(med, dtype=float)
        positive_vals.extend(vals[np.isfinite(vals) & (vals > 0)].tolist())
        bars = ax.bar(x + (bi - 0.5) * width, vals, width=width,
                      label=(r"$G\rightarrow G$" if branch == "circuit" else r"$H\rightarrow G$"))
        # P90 shown as small horizontal markers above the matching bar.
        for bar, q in zip(bars, p90):
            if np.isfinite(q):
                cx = bar.get_x() + bar.get_width() / 2
                ax.plot([cx - width * 0.22, cx + width * 0.22], [q, q], color="black", lw=1.0)
    if positive_vals and max(positive_vals) / max(min(positive_vals), 1e-12) > 50:
        ax.set_yscale("log")
    ax.set_xticks(x)
    ax.set_xticklabels(params, rotation=25, ha="right")
    ax.set_ylabel("Absolute relative error [%]")
    ax.set_xlabel("Physical circuit parameter")
    ax.legend(frameon=False, ncol=2)
    ax.grid(axis="y", alpha=0.2)
    ax.text(0.99, 0.98, "bar = median; black marker = P90", transform=ax.transAxes,
            ha="right", va="top", fontsize=8)
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, bbox_inches="tight")
    plt.close(fig)


def plot_hamiltonian_errors(aggregate_rows: list[dict[str, Any]], out_path: Path) -> None:
    categories = ["frequency", "self_kerr", "cross_kerr", "kappa"]
    branch_order = [b for b in ["spec", "circuit"] if any(r["branch"] == b for r in aggregate_rows)]
    if not branch_order:
        return
    labels = {
        "frequency": r"$f_i$",
        "self_kerr": r"$\chi_{ii}$",
        "cross_kerr": r"$\chi_{ij}$",
        "kappa": r"$\kappa_i$",
    }
    x = np.arange(len(categories), dtype=float)
    width = 0.36 if len(branch_order) > 1 else 0.52
    fig, ax = plt.subplots(figsize=(7.4, 4.5))
    all_med = []
    for bi, branch in enumerate(branch_order):
        med, p90 = [], []
        for cat in categories:
            m = [r for r in aggregate_rows if r["branch"] == branch and r["category"] == cat]
            med.append(float(m[0]["median_relative_error_percent"]) if m else np.nan)
            p90.append(float(m[0]["p90_relative_error_percent"]) if m else np.nan)
        offset = (bi - (len(branch_order) - 1) / 2) * width
        bars = ax.bar(x + offset, med, width=width, label=(r"$H\rightarrow G$" if branch == "spec" else r"$G\rightarrow G$"))
        all_med.extend(v for v in med if np.isfinite(v) and v > 0)
        for bar, q in zip(bars, p90):
            if np.isfinite(q):
                cx = bar.get_x() + bar.get_width() / 2
                ax.plot([cx - width * 0.22, cx + width * 0.22], [q, q], color="black", lw=1.0)
    if all_med and max(all_med) / max(min(all_med), 1e-12) > 50:
        ax.set_yscale("log")
    ax.set_xticks(x)
    ax.set_xticklabels([labels[c] for c in categories])
    ax.set_ylabel("Absolute relative error [%]")
    ax.set_xlabel("Hamiltonian observable")
    ax.grid(axis="y", alpha=0.2)
    ax.legend(frameon=False)
    ax.text(0.99, 0.98, "bar = median; black marker = P90", transform=ax.transAxes,
            ha="right", va="top", fontsize=8)
    fig.tight_layout()
    out_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(out_path, bbox_inches="tight")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Final-summary helpers
# ---------------------------------------------------------------------------


def build_full_topology_rows(all_topo: list[dict[str, Any]]) -> list[dict[str, Any]]:
    rows = []
    branches = sorted({str(r["branch"]) for r in all_topo})
    for branch in branches:
        b = [r for r in all_topo if r["branch"] == branch]
        rows.append({"scope": "overall", "branch": branch, "family": "ALL", "family_display": "ALL", **aggregate_topology(b)})
        for family in sorted({str(r["family"]) for r in b}):
            f = [r for r in b if r["family"] == family]
            rows.append({"scope": "family", "branch": branch, "family": family, "family_display": pretty_family(family), **aggregate_topology(f)})
    return rows


def final_discussion_rows(
    full_topo: list[dict[str, Any]],
    node_errors: list[dict[str, Any]],
    param_agg: list[dict[str, Any]],
    ham_agg: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for branch in ["circuit", "spec"]:
        fam = [r for r in full_topo if r.get("scope") == "family" and r.get("branch") == branch]
        if fam:
            worst = min(fam, key=lambda r: finite_or_nan(r.get("topology_accuracy")))
            rows.append({
                "question": "largest_topology_error_family",
                "branch": branch,
                "result": worst["family_display"],
                "value": 1.0 - float(worst["topology_accuracy"]),
            })
        ne = [r for r in node_errors if r.get("branch") == branch and int(r.get("n_true", 0)) > 0]
        if ne:
            worst = max(ne, key=lambda r: finite_or_nan(r.get("error_rate")))
            rows.append({
                "question": "macro_node_with_largest_error_rate",
                "branch": branch,
                "result": worst["node_type"],
                "value": worst["error_rate"],
            })
        pe = [r for r in param_agg if r.get("branch") == branch and int(r.get("n", 0)) > 0]
        if pe:
            worst = max(pe, key=lambda r: finite_or_nan(r.get("median_relative_error_percent")))
            rows.append({
                "question": "hardest_physical_parameter",
                "branch": branch,
                "result": worst["parameter_base"],
                "value": worst["median_relative_error_percent"],
            })

    ham_spec = [r for r in ham_agg if r.get("branch") == "spec" and int(r.get("n", 0)) > 0]
    if ham_spec:
        worst = max(ham_spec, key=lambda r: finite_or_nan(r.get("median_relative_error_percent")))
        rows.append({
            "question": "hamiltonian_observable_with_largest_median_error",
            "branch": "spec",
            "result": worst["category"],
            "value": worst["median_relative_error_percent"],
        })

    overall_c = next((r for r in full_topo if r.get("scope") == "overall" and r.get("branch") == "circuit"), None)
    overall_s = next((r for r in full_topo if r.get("scope") == "overall" and r.get("branch") == "spec"), None)
    if overall_c and overall_s:
        drop = float(overall_c["topology_accuracy"]) - float(overall_s["topology_accuracy"])
        rows.append({
            "question": "topology_accuracy_drop_G_to_G_vs_H_to_G",
            "branch": "comparison",
            "result": "percentage-point drop",
            "value": drop * 100.0,
        })
    return rows


# ---------------------------------------------------------------------------
# CLI / main
# ---------------------------------------------------------------------------


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Sec. 4.3.1 seen-circuit inference analysis for cQED-Gen")
    p.add_argument("--ckpt", default="best_vae_global.pt")
    p.add_argument("--split", default="test", choices=["train", "val", "test"])
    p.add_argument("--out-dir", default="analysis_results/4_3_1_seen_circuits")
    p.add_argument("--batch-size", type=int, default=128)
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--runs", type=int, default=10, help="Independent metric subsampling runs.")
    p.add_argument("--samples-per-run", type=int, default=500, help="M circuits per repeated topology study.")
    p.add_argument("--max-per-family", type=int, default=0, help="Diagnostic cap for neural inference; 0 = use full split.")
    p.add_argument("--stochastic", action="store_true", help="Use stochastic decoder sampling. Default is deterministic.")
    p.add_argument("--no-permutation-eval", action="store_true")
    p.add_argument("--no-qultra", action="store_true")
    p.add_argument("--qultra-branches", default="spec", choices=["spec", "circuit", "both"],
                   help="Which branch(es) receive QuLTRA physical validation.")
    p.add_argument("--qultra-max-per-family", type=int, default=0,
                   help="Max QuLTRA attempts per family/selected branch; 0 = all samples (default).")
    p.add_argument("--f-min", type=float, default=1.0)
    p.add_argument("--f-max", type=float, default=9.0)
    p.add_argument("--scaler-atol", type=float, default=1e-9)
    return p.parse_args()


def main() -> None:
    args = parse_args()
    set_seed(args.seed)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Repository : {REPO_ROOT}")
    print(f"Device     : {device}")
    print(f"Checkpoint : {args.ckpt}")
    print(f"Split      : {args.split}")

    ckpt_path = Path(args.ckpt)
    if not ckpt_path.is_absolute():
        ckpt_path = REPO_ROOT / ckpt_path
    if not ckpt_path.exists():
        raise FileNotFoundError(ckpt_path)

    # Repository checkpoint loader reconstructs model + exact saved scaler dict.
    model, checkpoint_scalers, cfg = ice.load_checkpoint(str(ckpt_path), device)

    print("\nReconstructing deterministic dataset split...")
    train_data, val_data, test_data, fresh_scalers = load_all_datasets_vae(
        train_frac=cfg.get("train_frac", 0.70),
        val_frac=cfg.get("val_frac", 0.15),
        seed=cfg.get("seed", args.seed),
        max_nodes=cfg.get("max_nodes", 12),
    )
    scalers = checkpoint_scalers_for_families(checkpoint_scalers, fresh_scalers)
    verify_scaler_consistency(scalers, fresh_scalers, atol=args.scaler_atol)

    split_data = {"train": train_data, "val": val_data, "test": test_data}[args.split]
    # Seen-circuit thesis analysis should normally remain on the TEST split.
    if args.split != "test":
        print("WARNING: Sec. 4.3.1 is intended for the test split; you selected", args.split)
    data = optionally_limit_per_family(split_data, args.max_per_family, args.seed)
    print(f"Samples selected: {len(data)}")
    for family, items in sorted(group_by_family(data).items()):
        print(f"  {pretty_family(family):28s}: {len(items)}")

    qultra_branch_set = {
        "spec": {"spec"},
        "circuit": {"circuit"},
        "both": {"circuit", "spec"},
    }[args.qultra_branches]

    all_topo: list[dict[str, Any]] = []
    all_confusion: list[dict[str, Any]] = []
    all_params: list[dict[str, Any]] = []
    all_ham: list[dict[str, Any]] = []
    all_qultra_status: list[dict[str, Any]] = []

    for branch in ("circuit", "spec"):
        print("\n" + "=" * 82)
        print("CIRCUIT BRANCH G -> z_c -> G" if branch == "circuit" else "HAMILTONIAN BRANCH H -> z_s -> G")
        print("=" * 82)
        result = evaluate_branch(
            model=model,
            data=data,
            scalers=scalers,
            device=device,
            branch=branch,
            batch_size=args.batch_size,
            stochastic=args.stochastic,
            use_permutation_eval=not args.no_permutation_eval,
            qultra_enabled=(not args.no_qultra and branch in qultra_branch_set),
            qultra_max_per_family=args.qultra_max_per_family,
            f_min=args.f_min,
            f_max=args.f_max,
            seed=args.seed,
        )
        all_topo.extend(result["topology_records"])
        all_confusion.extend(result["confusion_pairs"])
        all_params.extend(result["parameter_rows"])
        all_ham.extend(result["hamiltonian_rows"])
        all_qultra_status.extend(result["qultra_status"])

    # ------------------------------------------------------------------
    # Topology tables and repeated M=500, N=10 studies
    # ------------------------------------------------------------------
    full_topo = build_full_topology_rows(all_topo)
    overall_runs, family_runs = repeated_topology_studies(
        all_topo,
        runs=args.runs,
        samples_per_run=args.samples_per_run,
        seed=args.seed + 101,
    )
    run_summary = summarize_run_rows(overall_runs, ["branch"])
    run_summary += summarize_run_rows(family_runs, ["branch", "family", "family_display"])

    node_errors = node_class_error_rows(all_confusion)
    confusion_counts = confusion_count_rows(all_confusion)

    # ------------------------------------------------------------------
    # Parameter tables
    # ------------------------------------------------------------------
    param_family = aggregate_error_rows(all_params, ["branch", "family", "family_display", "parameter"])
    param_aggregate = aggregate_error_rows(all_params, ["branch", "parameter_base"])

    # ------------------------------------------------------------------
    # QuLTRA/Hamiltonian tables
    # ------------------------------------------------------------------
    ham_family = aggregate_error_rows(all_ham, ["branch", "family", "family_display", "category", "observable"])
    ham_aggregate = aggregate_error_rows(all_ham, ["branch", "category"])

    # ------------------------------------------------------------------
    # Save all raw/aggregated outputs
    # ------------------------------------------------------------------
    write_csv(full_topo, out_dir / "seen_topology_full.csv")
    write_csv(overall_runs, out_dir / "seen_topology_runs_overall.csv")
    write_csv(family_runs, out_dir / "seen_topology_runs_per_family.csv")
    write_csv(run_summary, out_dir / "seen_topology_run_summary.csv")
    write_csv(node_errors, out_dir / "seen_node_type_error_by_class.csv")
    write_csv(confusion_counts, out_dir / "seen_node_confusion_counts.csv")

    write_csv(all_params, out_dir / "seen_parameter_errors_raw.csv")
    write_csv(param_family, out_dir / "seen_parameter_errors_by_family.csv")
    write_csv(param_aggregate, out_dir / "seen_parameter_errors_aggregate.csv")

    write_csv(all_ham, out_dir / "seen_hamiltonian_errors_raw.csv")
    write_csv(ham_family, out_dir / "seen_hamiltonian_errors_by_family.csv")
    write_csv(ham_aggregate, out_dir / "seen_hamiltonian_errors_aggregate.csv")
    write_csv(all_qultra_status, out_dir / "seen_qultra_status.csv")

    discussion = final_discussion_rows(full_topo, node_errors, param_aggregate, ham_aggregate)
    write_csv(discussion, out_dir / "seen_final_discussion_summary.csv")

    # ------------------------------------------------------------------
    # PDF diagnostics
    # ------------------------------------------------------------------
    plot_topology_metrics(full_topo, out_dir / "figure_seen_topology_metrics.pdf")
    plot_confusion(all_confusion, out_dir / "figure_seen_node_confusion.pdf")
    plot_parameter_errors(param_aggregate, out_dir / "figure_seen_parameter_errors.pdf")
    if ham_aggregate:
        plot_hamiltonian_errors(ham_aggregate, out_dir / "figure_seen_hamiltonian_errors.pdf")

    # ------------------------------------------------------------------
    # Headline summary for direct thesis insertion
    # ------------------------------------------------------------------
    headline: dict[str, Any] = {
        "checkpoint": str(ckpt_path),
        "split": args.split,
        "n_samples_total": len(data),
        "runs": args.runs,
        "samples_per_run": args.samples_per_run,
        "deterministic_inference": not args.stochastic,
        "topology_full": full_topo,
        "topology_repeated_run_summary": run_summary,
        "node_type_errors": node_errors,
        "parameter_error_aggregate": param_aggregate,
        "hamiltonian_error_aggregate": ham_aggregate,
        "qultra_status": all_qultra_status,
        "final_discussion": discussion,
    }
    (out_dir / "seen_inference_summary.json").write_text(
        json.dumps(jsonable(headline), indent=2), encoding="utf-8"
    )

    # Console headline.
    print("\n" + "=" * 82)
    print("HEADLINE RESULTS")
    print("=" * 82)
    for branch in ("circuit", "spec"):
        full = next(r for r in full_topo if r["scope"] == "overall" and r["branch"] == branch)
        rs = next(r for r in run_summary if r.get("branch") == branch and "family" not in r)
        name = "G -> G" if branch == "circuit" else "H -> G"
        print(
            f"{name:8s}: full A_topo={100*full['topology_accuracy']:.3f}% | "
            f"{args.runs}x{args.samples_per_run}: "
            f"{100*rs['topology_accuracy_mean']:.3f} +/- {100*rs['topology_accuracy_std']:.3f}% | "
            f"node={100*full['node_type_accuracy']:.3f}% | edge F1={full['edge_f1']:.5f} | "
            f"S_N={full['node_count_mae']:.5f}"
        )
    if ham_aggregate:
        print("\nHamiltonian relative-error medians / P90:")
        for r in ham_aggregate:
            print(
                f"  {r['branch']:7s} {r['category']:12s}: "
                f"median={r['median_relative_error_percent']:.4g}%  "
                f"P90={r['p90_relative_error_percent']:.4g}%  N={r['n']}"
            )
    print(f"\nOutputs -> {out_dir.resolve()}")


if __name__ == "__main__":
    main()
