"""
expansion.py
============

Inverse utilities for the cQED graph-compression basis.

`graphlize()` maps primitive cQED graphs (TRANSMON, RESONATOR, C_COUPLER,
I_COUPLER, FEEDLINE nodes) to macro graphs (TC, RC, RCT, TCT, RI, ...).  This
module implements the deterministic reverse map used by the specs -> z ->
g_macro branch: every macro node is expanded back to primitive blocks and the
macro edges are wired to primitive boundary ports.

The expansion intentionally works at the same primitive-block level used by the
raw datasets: Transmon / Resonator / C_coupler / I_coupler / Feedline.  It does
not expand a Transmon into L-C internal elements, nor a Resonator into length
parameter nodes.
"""

from __future__ import annotations

import math
import re
from dataclasses import dataclass
from typing import Iterable

from circuit2graph.definitions import SubgType
from circuit2graph.topology import CQEDNode, CQEDTopology


PRIMITIVE_TYPES = {
    SubgType.FEEDLINE,
    SubgType.TRANSMON,
    SubgType.RESONATOR,
    SubgType.C_COUPLER,
    SubgType.I_COUPLER,
}


@dataclass(frozen=True)
class _PrimitiveSpec:
    subg_type: SubgType
    attrs: dict
    label: str | None


def _direction(attrs: dict) -> float:
    """Return +1/-1 from attrs['dir']; default to canonical order (+1)."""
    try:
        return 1.0 if float(attrs.get("dir", 1.0)) >= 0.0 else -1.0
    except (TypeError, ValueError):
        return 1.0


def _split_macro_label(label: str | None, expected: int) -> list[str | None]:
    """
    Parse labels generated by compression, e.g. ``RCT(T1+Cc+R1)``.

    Predicted/generated macro graphs often do not carry labels; in that case we
    return placeholders and the expander will synthesize deterministic labels.
    """
    if not label:
        return [None] * expected
    match = re.search(r"\((.*)\)\s*$", label)
    if not match:
        return [None] * expected
    parts = match.group(1).split("+")
    if len(parts) != expected:
        return [None] * expected
    return parts


def _label(base: str, node_id: int, idx: int, parsed: str | None) -> str:
    return parsed if parsed is not None else f"{base}_{node_id}_{idx}"


def expand_node_to_primitives(node: CQEDNode) -> list[_PrimitiveSpec]:
    """
    Expand one compressed/macro CQEDNode into an ordered primitive chain.

    Direction conventions mirror `compression.py`:
    - TC:  dir=+1 -> T-C,   dir=-1 -> C-T
    - RC:  dir=+1 -> R-C,   dir=-1 -> C-R
    - RI:  dir=+1 -> R-Ind, dir=-1 -> Ind-R
    - RCT: dir=+1 -> R-C-T, dir=-1 -> T-C-R
    - TCT stores both transmons in deterministic traversal order: T-C-T
    """
    st = node.subg_type
    a = node.attrs

    if st in PRIMITIVE_TYPES:
        return [_PrimitiveSpec(st, dict(a), node.label)]

    if st == SubgType.TC:
        parsed = _split_macro_label(node.label, 2)
        t = _PrimitiveSpec(SubgType.TRANSMON, {"L": a.get("L", 0.0), "C": a.get("C", 0.0)}, _label("T", node.node_id, 0, parsed[0 if _direction(a) > 0 else 1]))
        c = _PrimitiveSpec(SubgType.C_COUPLER, {"Cc": a.get("Cc", 0.0)}, _label("C", node.node_id, 1, parsed[1 if _direction(a) > 0 else 0]))
        return [t, c] if _direction(a) > 0 else [c, t]

    if st == SubgType.RC:
        parsed = _split_macro_label(node.label, 2)
        r = _PrimitiveSpec(SubgType.RESONATOR, {"length": a.get("length", 0.0)}, _label("R", node.node_id, 0, parsed[0 if _direction(a) > 0 else 1]))
        c = _PrimitiveSpec(SubgType.C_COUPLER, {"Cc": a.get("Cc", 0.0)}, _label("C", node.node_id, 1, parsed[1 if _direction(a) > 0 else 0]))
        return [r, c] if _direction(a) > 0 else [c, r]

    if st == SubgType.RI:
        parsed = _split_macro_label(node.label, 2)
        r = _PrimitiveSpec(SubgType.RESONATOR, {"length": a.get("length", 0.0)}, _label("R", node.node_id, 0, parsed[0 if _direction(a) > 0 else 1]))
        ind = _PrimitiveSpec(SubgType.I_COUPLER, {"D": a.get("D", 0.0), "l": a.get("l", 0.0)}, _label("Ind", node.node_id, 1, parsed[1 if _direction(a) > 0 else 0]))
        return [r, ind] if _direction(a) > 0 else [ind, r]

    if st == SubgType.RCT:
        parsed = _split_macro_label(node.label, 3)
        if _direction(a) > 0:
            return [
                _PrimitiveSpec(SubgType.RESONATOR, {"length": a.get("length", 0.0)}, _label("R", node.node_id, 0, parsed[0])),
                _PrimitiveSpec(SubgType.C_COUPLER, {"Cc": a.get("Cc", 0.0)}, _label("C", node.node_id, 1, parsed[1])),
                _PrimitiveSpec(SubgType.TRANSMON, {"L": a.get("L", 0.0), "C": a.get("C", 0.0)}, _label("T", node.node_id, 2, parsed[2])),
            ]
        return [
            _PrimitiveSpec(SubgType.TRANSMON, {"L": a.get("L", 0.0), "C": a.get("C", 0.0)}, _label("T", node.node_id, 0, parsed[0])),
            _PrimitiveSpec(SubgType.C_COUPLER, {"Cc": a.get("Cc", 0.0)}, _label("C", node.node_id, 1, parsed[1])),
            _PrimitiveSpec(SubgType.RESONATOR, {"length": a.get("length", 0.0)}, _label("R", node.node_id, 2, parsed[2])),
        ]

    if st == SubgType.TCT:
        parsed = _split_macro_label(node.label, 3)
        return [
            _PrimitiveSpec(SubgType.TRANSMON, {"L": a.get("L", 0.0), "C": a.get("C", 0.0)}, _label("T", node.node_id, 0, parsed[0])),
            _PrimitiveSpec(SubgType.C_COUPLER, {"Cc": a.get("Cc", 0.0)}, _label("C", node.node_id, 1, parsed[1])),
            _PrimitiveSpec(SubgType.TRANSMON, {"L": a.get("L2", 0.0), "C": a.get("C2", 0.0)}, _label("T", node.node_id, 2, parsed[2])),
        ]

    raise ValueError(f"Cannot expand unknown SubgType {st!r}.")


def _copy_with_edges(node_specs: dict[int, list[_PrimitiveSpec]], assignments: dict[tuple[int, int], tuple[int, int]], name: str) -> CQEDTopology:
    """Materialize primitive nodes, internal chain edges and assigned macro edges.

    `assignments` is keyed by the ORIENTED macro edge `(u_old, v_old)`.
    Do not collapse that key to `frozenset`: the boundary indices are directional
    (`max_index(u_old) -> min_index(v_old)`).
    """
    out = CQEDTopology(name=name)
    primitive_ids: dict[tuple[int, int], CQEDNode] = {}

    for old_id in sorted(node_specs):
        for idx, spec in enumerate(node_specs[old_id]):
            primitive_ids[(old_id, idx)] = out.add_node(spec.subg_type, dict(spec.attrs), label=spec.label)
        for idx in range(len(node_specs[old_id]) - 1):
            out.add_edge(primitive_ids[(old_id, idx)], primitive_ids[(old_id, idx + 1)])

    seen: set[frozenset[int]] = {frozenset(e) for e in out._edges}
    for (u_old, v_old), (u_idx, v_idx) in sorted(assignments.items()):
        a = primitive_ids[(u_old, u_idx)]
        b = primitive_ids[(v_old, v_idx)]
        edge_key = frozenset({a.node_id, b.node_id})
        if a.node_id != b.node_id and edge_key not in seen:
            out.add_edge(a, b)
            seen.add(edge_key)
    return out


def _attrs_close(a: dict, b: dict, tol: float = 1e-12) -> bool:
    keys = set(a) | set(b)
    for k in keys:
        av = a.get(k, 0.0)
        bv = b.get(k, 0.0)
        if isinstance(av, (int, float)) and isinstance(bv, (int, float)):
            if not math.isclose(float(av), float(bv), rel_tol=tol, abs_tol=tol):
                return False
        elif av != bv:
            return False
    return True


def topologies_equivalent(a: CQEDTopology, b: CQEDTopology, *, check_labels: bool = False) -> bool:
    """NetworkX isomorphism helper used by tests and optional validation."""
    import networkx as nx

    def to_nx(t: CQEDTopology) -> nx.Graph:
        g = nx.Graph()
        for n in t._nodes:
            g.add_node(n.node_id, subg_type=n.subg_type, attrs=n.attrs, label=n.label)
        g.add_edges_from(t._edges)
        return g

    def node_match(x: dict, y: dict) -> bool:
        if x["subg_type"] != y["subg_type"]:
            return False
        if check_labels and x.get("label") != y.get("label"):
            return False
        return _attrs_close(x.get("attrs", {}), y.get("attrs", {}))

    return nx.is_isomorphic(to_nx(a), to_nx(b), node_match=node_match)


def _validate_recompress(candidate: CQEDTopology, target: CQEDTopology) -> bool:
    """Return True when graphlize(candidate) reproduces target up to isomorphism."""
    from circuit2graph.compression import graphlize

    recompressed = graphlize(candidate)
    return topologies_equivalent(recompressed, target, check_labels=False)



def _macro_adjacency(topology: CQEDTopology) -> dict[int, list[int]]:
    """Return a deterministic undirected adjacency map for a macro topology."""
    adj: dict[int, list[int]] = {n.node_id: [] for n in topology._nodes}
    for u, v in topology._edges:
        if u == v:
            continue
        if u in adj and v in adj:
            adj[u].append(v)
            adj[v].append(u)
    return {nid: sorted(set(nbrs)) for nid, nbrs in adj.items()}


def _walk_simple_cycle(start: int, adj: dict[int, list[int]]) -> list[int]:
    """
    Deterministically orient a degree-2 component.

    There is no geometric embedding in CQEDTopology, so "anticlockwise" cannot
    be recovered literally after compression.  We define the recoverable
    equivalent as one consistent cyclic orientation: start from the chosen root
    and follow the lowest-id neighbour first.
    """
    cycle = [start]
    prev: int | None = None
    curr = start

    while True:
        nbrs = adj[curr]
        if prev is None:
            nxt = nbrs[0]
        else:
            candidates = [n for n in nbrs if n != prev]
            if not candidates:
                break
            nxt = candidates[0]

        if nxt == start:
            break
        if nxt in cycle:
            # Not a clean simple cycle; return the partial deterministic walk.
            break
        cycle.append(nxt)
        prev, curr = curr, nxt

    return cycle


def _oriented_macro_edges(topology: CQEDTopology, *, root_id: int | None = None) -> list[tuple[int, int]]:
    """
    Orient compressed edges in the same direction used for expansion.

    * Tree/line components: root -> leaves by BFS levels.
    * Simple cycles: one consistent cyclic orientation from the component root.

    Compression does not currently store the original primitive root explicitly.
    In graphs produced by graphlize(), the first emitted compressed node has
    node_id == 0 and corresponds to the traversal root.  For generated macro
    graphs, using the lowest node_id gives a deterministic root and keeps the
    expansion invariant to which macro-node was chosen as long as the same
    orientation rule is followed.
    """
    adj = _macro_adjacency(topology)
    if not adj:
        return []

    all_edges = {frozenset({u, v}) for u, nbrs in adj.items() for v in nbrs if u != v}
    oriented: list[tuple[int, int]] = []
    oriented_keys: set[frozenset[int]] = set()
    visited: set[int] = set()

    def add(u: int, v: int) -> None:
        key = frozenset({u, v})
        if u != v and key in all_edges and key not in oriented_keys:
            oriented.append((u, v))
            oriented_keys.add(key)

    component_roots = []
    if root_id is not None and root_id in adj:
        component_roots.append(root_id)
    component_roots.extend(nid for nid in sorted(adj) if nid not in component_roots)

    for comp_root in component_roots:
        if comp_root in visited:
            continue

        # Collect the component.
        queue = [comp_root]
        component: list[int] = []
        visited.add(comp_root)
        while queue:
            u = queue.pop(0)
            component.append(u)
            for v in adj[u]:
                if v not in visited:
                    visited.add(v)
                    queue.append(v)

        component_set = set(component)
        is_simple_cycle = (
            len(component) > 2
            and all(len([v for v in adj[n] if v in component_set]) == 2 for n in component)
        )

        if is_simple_cycle:
            cycle = _walk_simple_cycle(comp_root, adj)
            if len(cycle) == len(component):
                for a, b in zip(cycle, cycle[1:]):
                    add(a, b)
                add(cycle[-1], cycle[0])
                continue

        # Default: orient a spanning traversal from the component root to leaves.
        # Any remaining non-tree/cross edge is oriented from lower BFS rank to
        # higher BFS rank; ties fall back to node_id for determinism.
        parent: dict[int, int | None] = {comp_root: None}
        rank: dict[int, tuple[int, int]] = {comp_root: (0, comp_root)}
        queue = [comp_root]
        while queue:
            u = queue.pop(0)
            for v in adj[u]:
                if v in component_set and v not in parent:
                    parent[v] = u
                    rank[v] = (rank[u][0] + 1, v)
                    add(u, v)
                    queue.append(v)

        for key in sorted(all_edges, key=lambda k: tuple(sorted(k))):
            u, v = tuple(key)
            if u not in component_set or v not in component_set or key in oriented_keys:
                continue
            if rank.get(u, (10**9, u)) <= rank.get(v, (10**9, v)):
                add(u, v)
            else:
                add(v, u)

    return oriented


def _edge_assignments_from_orientation(
    node_specs: dict[int, list[_PrimitiveSpec]],
    oriented_edges: list[tuple[int, int]],
) -> dict[tuple[int, int], tuple[int, int]]:
    """
    Map each oriented macro edge u -> v to primitive boundary indices.

    The rule is intentionally simple and order-preserving:
    - leave u from its highest primitive index;
    - enter v at its lowest primitive index.

    Because expand_node_to_primitives() has already applied attrs['dir'], the
    lowest/highest indices are exactly the macro-node boundaries in traversal
    order.  Primitive singletons use index 0 for both sides.
    """
    assignments: dict[tuple[int, int], tuple[int, int]] = {}
    for u, v in oriented_edges:
        u_idx = len(node_specs[u]) - 1
        v_idx = 0
        assignments[(u, v)] = (u_idx, v_idx)
    return assignments


def expand_topology(compressed: CQEDTopology, *, validate: bool = False, max_solutions: int = 20000) -> CQEDTopology:
    """
    Expand a macro CQEDTopology back to primitive CQEDTopology.

    The external wiring is directional rather than search-based: compressed
    edges are first oriented root->leaf for line/tree components, or in one
    consistent cyclic direction for loop components.  Then every oriented edge
    u -> v is wired from max_index(u) to min_index(v).  This preserves the
    primitive order induced by attrs['dir'] and keeps each node's attributes on
    the primitive created for that position.

    Notes
    -----
    `validate` and `max_solutions` are kept in the signature for backward
    compatibility with the older backtracking implementation; they are not used
    by the directional assignment.
    """
    node_specs = {n.node_id: expand_node_to_primitives(n) for n in compressed._nodes}
    if not node_specs:
        return CQEDTopology(name=f"{compressed.name}__expanded")

    root_id = 0 if 0 in node_specs else min(node_specs)
    oriented_edges = _oriented_macro_edges(compressed, root_id=root_id)
    assignments = _edge_assignments_from_orientation(node_specs, oriented_edges)
    return _copy_with_edges(node_specs, assignments, f"{compressed.name}__expanded")


# Backward-compatible aliases that are pleasant to import in notebooks/tests.
expand_graph = expand_topology
expand_macro_graph = expand_topology
