"""
expansion.py
============

Inverse utilities for the cQED graph-compression basis.

`graphlize()` maps primitive cQED graphs (TRANSMON, RESONATOR, C_COUPLER,
I_COUPLER, FEEDLINE nodes) to macro graphs (TC, RC, RCT, TCT, RI, ...).  This
module implements the deterministic reverse map used by the specs -> z ->
g_macro branch: every macro node is expanded back to primitive blocks and the
macro edges are wired to primitive boundary ports.

The expansion intentionally works at the same primitive-block level used by the
raw datasets: Transmon / Resonator / C_coupler / I_coupler / Feedline.  It does
not expand a Transmon into L-C internal elements, nor a Resonator into length
parameter nodes.
"""

from __future__ import annotations

import math
import re
from dataclasses import dataclass
from typing import Iterable

from circuit2graph.definitions import SubgType
from circuit2graph.topology import CQEDNode, CQEDTopology


PRIMITIVE_TYPES = {
    SubgType.FEEDLINE,
    SubgType.TRANSMON,
    SubgType.RESONATOR,
    SubgType.C_COUPLER,
    SubgType.I_COUPLER,
}


@dataclass(frozen=True)
class _PrimitiveSpec:
    subg_type: SubgType
    attrs: dict
    label: str | None


def _direction(attrs: dict) -> float:
    """Return +1/-1 from attrs['dir']; default to canonical order (+1)."""
    try:
        return 1.0 if float(attrs.get("dir", 1.0)) >= 0.0 else -1.0
    except (TypeError, ValueError):
        return 1.0


def _split_macro_label(label: str | None, expected: int) -> list[str | None]:
    """
    Parse labels generated by compression, e.g. ``RCT(T1+Cc+R1)``.

    Predicted/generated macro graphs often do not carry labels; in that case we
    return placeholders and the expander will synthesize deterministic labels.
    """
    if not label:
        return [None] * expected
    match = re.search(r"\((.*)\)\s*$", label)
    if not match:
        return [None] * expected
    parts = match.group(1).split("+")
    if len(parts) != expected:
        return [None] * expected
    return parts


def _label(base: str, node_id: int, idx: int, parsed: str | None) -> str:
    return parsed if parsed is not None else f"{base}_{node_id}_{idx}"


def expand_node_to_primitives(node: CQEDNode) -> list[_PrimitiveSpec]:
    """
    Expand one compressed/macro CQEDNode into an ordered primitive chain.

    Direction conventions mirror `compression.py`:
    - TC:  dir=+1 -> T-C,   dir=-1 -> C-T
    - RC:  dir=+1 -> R-C,   dir=-1 -> C-R
    - RI:  dir=+1 -> R-Ind, dir=-1 -> Ind-R
    - RCT: dir=+1 -> R-C-T, dir=-1 -> T-C-R
    - TCT stores both transmons in deterministic traversal order: T-C-T
    """
    st = node.subg_type
    a = node.attrs

    if st in PRIMITIVE_TYPES:
        return [_PrimitiveSpec(st, dict(a), node.label)]

    if st == SubgType.TC:
        parsed = _split_macro_label(node.label, 2)
        t = _PrimitiveSpec(SubgType.TRANSMON, {"L": a.get("L", 0.0), "C": a.get("C", 0.0)}, _label("T", node.node_id, 0, parsed[0 if _direction(a) > 0 else 1]))
        c = _PrimitiveSpec(SubgType.C_COUPLER, {"Cc": a.get("Cc", 0.0)}, _label("C", node.node_id, 1, parsed[1 if _direction(a) > 0 else 0]))
        return [t, c] if _direction(a) > 0 else [c, t]

    if st == SubgType.RC:
        parsed = _split_macro_label(node.label, 2)
        r = _PrimitiveSpec(SubgType.RESONATOR, {"length": a.get("length", 0.0)}, _label("R", node.node_id, 0, parsed[0 if _direction(a) > 0 else 1]))
        c = _PrimitiveSpec(SubgType.C_COUPLER, {"Cc": a.get("Cc", 0.0)}, _label("C", node.node_id, 1, parsed[1 if _direction(a) > 0 else 0]))
        return [r, c] if _direction(a) > 0 else [c, r]

    if st == SubgType.RI:
        parsed = _split_macro_label(node.label, 2)
        r = _PrimitiveSpec(SubgType.RESONATOR, {"length": a.get("length", 0.0)}, _label("R", node.node_id, 0, parsed[0 if _direction(a) > 0 else 1]))
        ind = _PrimitiveSpec(SubgType.I_COUPLER, {"D": a.get("D", 0.0), "l": a.get("l", 0.0)}, _label("Ind", node.node_id, 1, parsed[1 if _direction(a) > 0 else 0]))
        return [r, ind] if _direction(a) > 0 else [ind, r]

    if st == SubgType.RCT:
        parsed = _split_macro_label(node.label, 3)
        if _direction(a) > 0:
            return [
                _PrimitiveSpec(SubgType.RESONATOR, {"length": a.get("length", 0.0)}, _label("R", node.node_id, 0, parsed[0])),
                _PrimitiveSpec(SubgType.C_COUPLER, {"Cc": a.get("Cc", 0.0)}, _label("C", node.node_id, 1, parsed[1])),
                _PrimitiveSpec(SubgType.TRANSMON, {"L": a.get("L", 0.0), "C": a.get("C", 0.0)}, _label("T", node.node_id, 2, parsed[2])),
            ]
        return [
            _PrimitiveSpec(SubgType.TRANSMON, {"L": a.get("L", 0.0), "C": a.get("C", 0.0)}, _label("T", node.node_id, 0, parsed[0])),
            _PrimitiveSpec(SubgType.C_COUPLER, {"Cc": a.get("Cc", 0.0)}, _label("C", node.node_id, 1, parsed[1])),
            _PrimitiveSpec(SubgType.RESONATOR, {"length": a.get("length", 0.0)}, _label("R", node.node_id, 2, parsed[2])),
        ]

    if st == SubgType.TCT:
        parsed = _split_macro_label(node.label, 3)
        return [
            _PrimitiveSpec(SubgType.TRANSMON, {"L": a.get("L", 0.0), "C": a.get("C", 0.0)}, _label("T", node.node_id, 0, parsed[0])),
            _PrimitiveSpec(SubgType.C_COUPLER, {"Cc": a.get("Cc", 0.0)}, _label("C", node.node_id, 1, parsed[1])),
            _PrimitiveSpec(SubgType.TRANSMON, {"L": a.get("L2", 0.0), "C": a.get("C2", 0.0)}, _label("T", node.node_id, 2, parsed[2])),
        ]

    raise ValueError(f"Cannot expand unknown SubgType {st!r}.")


def _copy_with_edges(node_specs: dict[int, list[_PrimitiveSpec]], assignments: dict[frozenset, tuple[int, int]], name: str) -> CQEDTopology:
    """Materialize primitive nodes, internal chain edges and assigned macro edges."""
    out = CQEDTopology(name=name)
    primitive_ids: dict[tuple[int, int], CQEDNode] = {}

    for old_id in sorted(node_specs):
        for idx, spec in enumerate(node_specs[old_id]):
            primitive_ids[(old_id, idx)] = out.add_node(spec.subg_type, dict(spec.attrs), label=spec.label)
        for idx in range(len(node_specs[old_id]) - 1):
            out.add_edge(primitive_ids[(old_id, idx)], primitive_ids[(old_id, idx + 1)])

    seen: set[frozenset[int]] = {frozenset(e) for e in out._edges}
    for key in sorted(assignments, key=lambda k: tuple(sorted(k))):
        u_old, v_old = tuple(key)
        u_idx, v_idx = assignments[key]
        a = primitive_ids[(u_old, u_idx)]
        b = primitive_ids[(v_old, v_idx)]
        edge_key = frozenset({a.node_id, b.node_id})
        if a.node_id != b.node_id and edge_key not in seen:
            out.add_edge(a, b)
            seen.add(edge_key)
    return out


def _attrs_close(a: dict, b: dict, tol: float = 1e-12) -> bool:
    keys = set(a) | set(b)
    for k in keys:
        av = a.get(k, 0.0)
        bv = b.get(k, 0.0)
        if isinstance(av, (int, float)) and isinstance(bv, (int, float)):
            if not math.isclose(float(av), float(bv), rel_tol=tol, abs_tol=tol):
                return False
        elif av != bv:
            return False
    return True


def topologies_equivalent(a: CQEDTopology, b: CQEDTopology, *, check_labels: bool = False) -> bool:
    """NetworkX isomorphism helper used by tests and optional validation."""
    import networkx as nx

    def to_nx(t: CQEDTopology) -> nx.Graph:
        g = nx.Graph()
        for n in t._nodes:
            g.add_node(n.node_id, subg_type=n.subg_type, attrs=n.attrs, label=n.label)
        g.add_edges_from(t._edges)
        return g

    def node_match(x: dict, y: dict) -> bool:
        if x["subg_type"] != y["subg_type"]:
            return False
        if check_labels and x.get("label") != y.get("label"):
            return False
        return _attrs_close(x.get("attrs", {}), y.get("attrs", {}))

    return nx.is_isomorphic(to_nx(a), to_nx(b), node_match=node_match)


def _validate_recompress(candidate: CQEDTopology, target: CQEDTopology) -> bool:
    """Return True when graphlize(candidate) reproduces target up to isomorphism."""
    from circuit2graph.compression import graphlize

    recompressed = graphlize(candidate)
    return topologies_equivalent(recompressed, target, check_labels=False)


def expand_topology(compressed: CQEDTopology, *, validate: bool = True, max_solutions: int = 20000) -> CQEDTopology:
    """
    Expand a macro CQEDTopology back to primitive CQEDTopology.

    Parameters
    ----------
    compressed:
        Macro graph produced by `graphlize()` or by a model in the same macro
        basis.
    validate:
        If True, the port assignment is chosen so that recompressing the
        expanded graph reproduces `compressed` whenever such an assignment is
        found.  If no validating assignment exists, the deterministic greedy
        assignment is returned.
    max_solutions:
        Safety cap for the backtracking search used to wire macro edges to
        primitive boundary ports.
    """
    node_specs = {n.node_id: expand_node_to_primitives(n) for n in compressed._nodes}
    if not node_specs:
        return CQEDTopology(name=f"{compressed.name}__expanded")

    # Boundary ports: primitive singletons have one unconstrained external port;
    # expanded macro chains expose their two chain endpoints, each at most once.
    boundary_ports: dict[int, list[int]] = {}
    port_capacity: dict[tuple[int, int], int | None] = {}
    for old_id, specs in node_specs.items():
        if len(specs) == 1:
            boundary_ports[old_id] = [0]
            port_capacity[(old_id, 0)] = None  # unlimited: primitive hub/root may have degree > 1
        else:
            boundary_ports[old_id] = [0, len(specs) - 1]
            port_capacity[(old_id, 0)] = 1
            port_capacity[(old_id, len(specs) - 1)] = 1

    edge_keys = []
    seen_edges = set()
    for u, v in compressed._edges:
        if u == v:
            continue
        key = frozenset({u, v})
        if key not in seen_edges:
            seen_edges.add(key)
            edge_keys.append(key)

    # Sort constrained edges first to prune faster.
    edge_keys.sort(key=lambda k: (sum(1 for nid in k if len(node_specs[nid]) > 1), tuple(sorted(k))), reverse=True)

    def candidates_for(key: frozenset) -> list[tuple[int, int]]:
        u, v = tuple(key)
        pairs = [(ui, vi) for ui in boundary_ports[u] for vi in boundary_ports[v]]
        # Deterministic preference: lower endpoint index first.  The validation
        # search will override this when the greedy choice is not invertible.
        return sorted(pairs)

    assignments: dict[frozenset, tuple[int, int]] = {}
    usage: dict[tuple[int, int], int] = {}
    attempts = 0
    first_complete: dict[frozenset, tuple[int, int]] | None = None
    valid_complete: dict[frozenset, tuple[int, int]] | None = None

    def available(old_id: int, idx: int) -> bool:
        cap = port_capacity[(old_id, idx)]
        return cap is None or usage.get((old_id, idx), 0) < cap

    def add_usage(old_id: int, idx: int, delta: int) -> None:
        key = (old_id, idx)
        usage[key] = usage.get(key, 0) + delta
        if usage[key] == 0:
            usage.pop(key)

    def search(pos: int) -> bool:
        nonlocal attempts, first_complete, valid_complete
        if attempts >= max_solutions:
            return False
        if pos == len(edge_keys):
            attempts += 1
            current = dict(assignments)
            if first_complete is None:
                first_complete = current
            candidate = _copy_with_edges(node_specs, current, f"{compressed.name}__expanded")
            if not validate or _validate_recompress(candidate, compressed):
                valid_complete = current
                return True
            return False

        key = edge_keys[pos]
        u, v = tuple(key)
        for ui, vi in candidates_for(key):
            if not available(u, ui) or not available(v, vi):
                continue
            assignments[key] = (ui, vi)
            add_usage(u, ui, +1)
            add_usage(v, vi, +1)
            if search(pos + 1):
                return True
            add_usage(u, ui, -1)
            add_usage(v, vi, -1)
            assignments.pop(key, None)
        return False

    search(0)
    chosen = valid_complete or first_complete or {}
    return _copy_with_edges(node_specs, chosen, f"{compressed.name}__expanded")


# Backward-compatible aliases that are pleasant to import in notebooks/tests.
expand_graph = expand_topology
expand_macro_graph = expand_topology
